services:
  frontend:
    build:
      context: .
      dockerfile: Dockerfile
      args:
        VITE_API_BASE_URL: "/api"
    ports:
      - "8080:80"
    depends_on:
      backend:
        condition: service_healthy
    restart: unless-stopped

  backend:
    image: node:20-alpine
    working_dir: /app
    ports:
      - "3001:3001"
    volumes:
      - ./db.json:/app/db.json
    command: >
      sh -lc "npm i -g json-server@0.17.4 &&
              json-server --watch /app/db.json --host 0.0.0.0 --port 3001 --cors"
    healthcheck:
      test: ["CMD", "node", "-e",
        "require('http').get('http://localhost:3001',
         r=>process.exit(r.statusCode===200?0:1)).on('error',()=>process.exit(1))"]
      interval: 5s
      timeout: 2s
      retries: 10
    restart: unless-stopped
